import Image from "next/image";

export default async function PrivacyPolicyPage() {
  //https://www.termsandconditionsgenerator.com/live.php?token=M5R5pvI4V0c1Wc25ZFLJUHJxic4YU5Ax
  return (
    <section className="mb-12 bg-black">
      {/* <div className="relative text-lg flex max-w-[80rem] w-full px-4 flex-col mx-auto gap-4  sm:px-6 lg:px-8 items-start justify-center pt-10 ">
        <span className="mr-2 rounded-full ">
          <div className=' flex h-10 justify-start items-start overflow-hidden gap-4 '>
            <Image src="/lib/image/b/CyanArrow_8a.svg" height={100} width={100} alt="Cyan Arrow" className=" w-10 "/>
            <h1 className="w-full text-4xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Terms and Conditions</h1>
          </div>
        </span>
        <p>Welcome to Cyan Arrow!</p>
        <p>These terms and conditions outline the rules and regulations for the use of Cyan Arrow's Website, located at www.cyanarrow.com.</p>
        <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use Cyan Arrow if you do not agree to take all of the terms and conditions stated on this page.</p>
        <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of in. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>
        
        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Cookies</h2>
        <p>We employ the use of cookies. By accessing Cyan Arrow, you agreed to use cookies in agreement with the Cyan Arrow's Privacy Policy. </p>
        <p>Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">License</h2>
        <p>Unless otherwise stated, Cyan Arrow and/or its licensors own the intellectual property rights for all material on Cyan Arrow. All intellectual property rights are reserved. You may access this from Cyan Arrow for your own personal use subjected to restrictions set in these terms and conditions.</p>
        <p>You must not:</p>
        <ul className=" list-disc list-inside">
            <li>Republish material from Cyan Arrow</li>
            <li>Sell, rent or sub-license material from Cyan Arrow</li>
            <li>Reproduce, duplicate or copy material from Cyan Arrow</li>
            <li>Redistribute content from Cyan Arrow</li>
        </ul>
        <p>This Agreement shall begin on the date hereof. </p>
          
        <p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Cyan Arrow does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Cyan Arrow,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Cyan Arrow shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>
        <p>Cyan Arrow reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>
        <p>You warrant and represent that:</p>
        <ul className=" list-disc list-inside">
            <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
            <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
            <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
            <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
        </ul>
        <p>You hereby grant Cyan Arrow a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Hyperlinking to our Content</h2>
        <p>The following organizations may link to our Website without prior written approval:</p>
        <ul className=" list-disc list-inside">
            <li>Government agencies;</li>
            <li>Search engines;</li>
            <li>News organizations;</li>
            <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
            <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
        </ul>
        <p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.</p>
        <p>We may consider and approve other link requests from the following types of organizations:</p>
        <ul className=" list-disc list-inside">
            <li>commonly-known consumer and/or business information sources;</li>
            <li>dot.com community sites;</li>
            <li>associations or other groups representing charities;</li>
            <li>online directory distributors;</li>
            <li>internet portals;</li>
            <li>accounting, law and consulting firms; and</li>
            <li>educational institutions and trade associations.</li>
        </ul>
        <p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Cyan Arrow; and (d) the link is in the context of general resource information.</p>
        <p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.</p>
        <p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Cyan Arrow. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>
        <p>Approved organizations may hyperlink to our Website as follows:</p>
        <ul className=" list-disc list-inside">
            <li>By use of our corporate name; or</li>
            <li>By use of the uniform resource locator being linked to; or</li>
            <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party's site.</li>
        </ul>
        <p>No use of Cyan Arrow's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">iFrames</h2>
        <p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Content Liability</h2>
        <p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Reservation of Rights</h2>
        <p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it's linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Removal of links from our website</h2>
        <p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>
        <p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>

        <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">Disclaimer</h2>
        <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>
        <ul className=" list-disc list-inside">
            <li>limit or exclude our or your liability for death or personal injury;</li>
            <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
            <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
            <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
        </ul>
        <p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>
        <p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>
      </div> */}
        <div className=" max-w-7xl text-lg mx-auto py-8 sm:py-24 px-4 sm:px-6 lg:px-8">
            <div className=" flex w-full flex-col">
                <span className="mr-2 rounded-full ">
                    <div className=' flex h-10 justify-start items-end overflow-hidden gap-4 '>
                        <Image src="/lib/image/b/CyanArrow_8a.svg" height={100} width={100} alt="Cyan Arrow" className=" w-10 "/>
                        <h1 className="text-4xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 ">Terms of Service</h1>
                        <p> (Last modified: August 15, 2023)</p>
                    </div>
                </span>
                
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">1. Introduction</h2>
                <p>These Terms of Service (“Terms”, “Terms of Service”) are used to determine the rules of the Service and to clarify the legal relationship between the entity using the Service and the Company. CyanArrow.com. (“Company”) operates web pages located at <a href="https://www.cyanarrow.com">www.cyanarrow.com</a> (“Website”) and offers Service (as defined below in Section 2).The Service is dedicated to the professional entities to help them to conduct their business. Using the Website and/or the Service in any manner, also by going through the Account registration process, the User or the Guest declares that (i) he/she has read, understood and accepts the provisions of the Terms and Privacy Policy, (ii) his/her age and legal capacity enables to conclude an agreement with the Company, (iii) he/she has the right to act on behalf of the entity which he/she represents and his/her declarations are effective. If the User does not agree to apply under the provisions of the Terms, he/she should not use the Service. In such a case however, the User may contact the Company by emailing at <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a> so the Company can try to find a solution.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">2. Definitions</h2>
                <p>Unless otherwise indicated, the following capitalizes terms have the following meaning:</p>
                <p><b>Account</b> – means individualized panel serving the User to exploit the Service and/or the Website.</p>
                <p><b>Agreement</b> – means a subscription agreement that may be concluded between User and the Company, that specifies the scope and the price for using the Service.</p>
                <p><b>API</b> – means Cyan Arrow application programming interface to be integrated with the User’s software.</p>
                <p><b>Company</b> – means CyanArrow.com,</p><p>
                <b>Content</b> – means the contents such as texts, pictures and other, which the Guest, or the User publishes, presents or sends on the Website or with the use of Service.</p>
                <p><b>Device</b> – means devices such as a computer, telephone, smartphone, tablet or other electronic equipment which allows browsing web pages.</p>
                <p><b>Guest</b> – means an entity browsing the Website.</p>
                <p><b>Intellectual Property</b> – means any designations, inventions, utility models, industrial designs, works and other externalized expressions of creative activity that are the subject of exclusive rights of the Company.</p>
                <p><b>Licence</b> – means a non-exclusive right to personal use of the API and/or the Widget.</p>
                <p><b>Link</b> – means hyperlink referring to the Other Website.</p>
                <p><b>Mobile Device</b> – means a portable device such as a telephone, smartphone, tablet or other electronic equipment which operates the Website and/or the Service.</p>
                <p><b>Notification</b> – means message sent to the User as part of the Service.</p>
                <p><b>Other Websites</b> – means websites other than the Website.</p>
                <p><b>Password</b> – means the User’s anonymized verification tool which enables the access to the Account and is the sequence of signs possibly to entry by using the keyboard of the computer or Mobile Device, which also allows entering text messages in the amount and configuration invented by the User however containing at least 8 signs.</p>
                <p><b>Privacy Policy</b> – means the Privacy Policy, which defines the rules of personal data processing by the Company, available under the following internet address: <a href="https://www.cyanarrow.com/privacy">https://www.cyanarrow.com/privacy</a>.</p>
                
                <p><b>Service</b> – means together the Website, Widget and/or the API (depending on the scope dedicated to a given User pursuant to the Agreement).</p>
                <p><b>Terms</b> – means these terms of service available under the following address: <a href="https://www.cyanarrow.com/terms">https://www.cyanarrow.com/terms</a>.</p>
                <p><b>User</b> – means an entity who owns the Account.</p>
                <p><b>Website</b> – means web pages located at <a href="https://www.cyanarrow.com">www.cyanarrow.com</a>.</p>
                <p><b>Widget</b> – means a Cyan Arrow widget that may be implemented to the User’s website.</p>
                <p>Above mentioned definitions retain their meaning regardless of whether they are expressed in the singular or the plural.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">3. General Rules</h2><p>Using the Service means full acceptance of the Terms. The Terms applies to relations between the Company and the Guest or the User only. If the Service and/or the Website introduces the possibility of providing services by other entities, they will be provided on the basis of regulations shared by these entities and only these entities will be responsible for the execution of the services, except the content of the Terms clearly and unambiguously indicates otherwise. Each entity using the Service and/or the Website is obliged to use it in accordance with its destiny resulting from the Terms. Using the Website is permissible provided that the Device meets jointly the following minimum technical requirements:</p>
                <ul className=" list-disc list-inside">
                    <li>has access to the Internet,</li>
                    <li>allows the start-up of the one from following internet browsers: (i) Google Chrome, (ii) Opera, (iii) Firefox, (iv) Safari, (v) Microsoft Edge,</li>
                    <li>the internet browser version used cannot be older than one year,</li>
                    <li>has JavaScript enabled.</li>
                </ul>
                <p>Using the API is possible if the following minimum technical requirements are met:</p>
                <ul className=" list-disc list-inside">
                    <li>has access to the Internet,</li>
                    <li>has software that enables sending HTTP requests.</li>
                </ul>
                <p>Using the Widget is possible if the following minimum technical requirements are met:</p>
                <ul className=" list-disc list-inside">
                    <li>has access to the Internet,</li>
                    <li>allows the start-up of the one from following internet browsers: (i) Google Chrome, (ii) Opera, (iii) Firefox, (iv) Safari, (v) Microsoft Edge,</li><li>the internet browser version used cannot be older than one year,</li>
                    <li>has JavaScript enabled.</li>
                </ul>
                <p>It is recommended to install anti-virus software on the Device or on the Mobile Device.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">4. Account</h2>
                <p>Account set-up is possible through the Website. Account set-up requires logging in using Facebook account, Google account or registering by providing other personal email and Password. When you create an Account you should provide us with accurate, complete, and current information at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on the Website and Service. You are responsible for maintaining the confidentiality of your Account and Password, including but not limited to the restriction of access to your Device or Mobile Device and/or Account. You agree to accept responsibility for any and all activities or actions that occur under your Account and/or Password, whether your Password is with our Website and Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your Account. You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">5. Communications</h2>
                <p>By creating an Account, you can agree to subscribe to newsletters, marketing or promotional materials and other information we may send. </p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">6. Contests, Sweepstakes and Promotions</h2><p>Any contests, sweepstakes or other promotions (collectively “Promotion(s)”) made available through Service or Website may be governed by rules that are separate from these Terms (in particular set out in the Agreement, if concluded). If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms, Promotion rules will apply.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">7. Subscriptions</h2>
                <p>Some parts of Service are billed on a subscription basis (“Subscription(s)”). You will be billed in advance on a recurring and periodic basis (“Billing Cycle”). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription. At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or the Company cancels it. You may cancel your Subscription renewal either through your Account or by contacting Company’s customer support team at <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a>. A valid payment method, including credit or debit card, Apple Pay or Google Pay, is required to process the payment for your subscription. You shall provide the Company with accurate and complete billing information including (i) full name, (ii) email address, (iii) country, (iv) business’s legal entity name, (v) VAT tax number and (vi) a valid payment method information. By submitting such payment information, you automatically authorize Company to charge all Subscription fees incurred through your Account to any such payment instruments. Should automatic billing fail to occur for any reason, Company will issue an electronic invoice indicating that you must proceed manually, within a certain deadline date, with the full payment corresponding to the billing period as indicated on the invoice. We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: service availability, errors in the description or price of the service, error in your order or other reasons. We reserve the right to refuse or cancel your order if fraud or an unauthorized or illegal transaction is suspected. Company is not responsible for any additional fees, including taxes, imposed by the relevant authorities of the country in which the person submitting an order resides / is located. Payment of these additional fees remains the responsibility of the person submitting the order.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">8. Fee Changes</h2>
                <p>The Company, in its sole discretion and at any time, may modify Subscription fees for the Subscriptions. Any Subscription fee change will become effective at the end of the then-current Billing Cycle. The Company will provide you with a reasonable prior notice of any change in Subscription fees to give you an opportunity to terminate your Subscription before such change becomes effective. Your continued use of Service after Subscription fee change comes into effect constitutes your agreement to pay the modified Subscription fee amount.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">9. Refunds</h2>
                <p>Except when required by law, paid Subscription fees are non-refundable.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">10. Content</h2>
                <p>Our Service and Website allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (“Content”). You are responsible, in particular to your customers, for Content that you post on or through Service including its legality, reliability, and appropriateness. By posting Content on or through Service or Website, You represent and warrant that: (i) Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and license as provided in these Terms, and (ii) that the posting of your Content on or through Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the Account of any User found to be infringing on a copyright. You retain any and all of your rights to any Content you submit, post or display on or through Service or Website and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through Service.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">11. Prohibited Uses</h2>
                <p>You may use Service or Website only for lawful purposes and in accordance with Terms. You agree not to use Service or Website:</p>
                <ul className=" list-disc list-inside">
                    <li>in any way that violates any applicable national or international law or regulation,</li>
                    <li>for the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise,</li>
                    <li>to transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter,” “spam,” or any other similar solicitation,</li>
                    <li>to impersonate or attempt to impersonate Company, a Company employee, another User, or any other person or entity,</li>
                    <li>in any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity,</li>
                    <li>to engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of Service or Website, or which, as determined by us, may harm or offend Company or Users of Service or Website or expose them to liability.</li>
                </ul>
                <p>Additionally, you agree not to:</p>
                <ul className=" list-disc list-inside">
                    <li>use Service and Website in any manner that could disable, overburden, damage, or impair Service or Website or interfere with any other party’s use of Service, including their ability to engage in real time activities through Service or Website,</li>
                    <li>use any robot, spider, or other automatic device, process, or means to access Service or Website for any purpose, including monitoring or copying any of the material on Service or Website,</li>
                    <li>use any manual process to monitor or copy any of the material on Service or Website or for any other unauthorized purpose without our prior written consent,</li>
                    <li>use any device, software, or routine that interferes with the proper working of Service or Website,</li>
                    <li>introduce any viruses, trojan horses, worms, logic bombs, or other material, which is malicious or technologically harmful,</li>
                    <li>attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service or Website, the server on which Service or Website is stored, or any server, computer, or database connected to Service or Website,</li>
                    <li>attack Service or Website via a denial-of-service attack or a distributed denial-of-service attack,</li>
                    <li>take any action that may damage or falsify Company rating,</li>
                    <li>otherwise attempt to interfere with the proper working of Service or Website.</li>
                </ul>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">12. Analytics</h2>
                <p>We may use third-party service providers to monitor and analyze the use of our Service and Website.</p>
                <p><b>Google Analytics</b></p>
                <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service and Website. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a>. We also encourage you to review the Google's policy for safeguarding your data: <a href="https://support.google.com/analytics/answer/6004245">https://support.google.com/analytics/answer/6004245</a>.</p>
                <p><b>Mixpanel</b></p>
                <p>Mixpanel is provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page: <a href="https://mixpanel.com/optout">https://mixpanel.com/optout</a>. For more information on what type of information Mixpanel collects, please visit the Terms of Use page of Mixpanel: <a href="https://mixpanel.com/terms">https://mixpanel.com/terms</a>.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">13. Intellectual Property</h2>
                <p>The Service, the Website and their original content (excluding Content), features and functionality are and will remain the exclusive property of the Company and its licensors. The Service and the Website are protected by copyright, trademark, and other laws of the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of the Company. The Guest and the User by using the Service do not acquire any rights to the Intellectual Property. It is prohibited to use the Intellectual Property for purposes other than those resulting from the authorized personal use referred to in the Article 23 of the Act of February 4, 1994 on Copyright and Related Rights. Upon purchase of a Subscription, the User receives the Licence to use the Service in accordance with the Subscription. The Licence is limited, non-transferable, revocable, non-exclusive and granted for a period consistent with the conditions of the Subscription. The User is not entitled to give a sublicense. The Licence is granted only in the following forms of exploitation:</p>
                <ul className=" list-disc list-inside">
                    <li>subscribing and installing the Service on the User’s website and/or software,</li>
                    <li>using the Service to serve the customers of the User.</li>
                </ul>
                <p>The User shall not modify, reverse engineer, decompile, disassemble or attempt to derive source code from Service or the Website or any portion thereof. The User is not entitled to create and/or publish APIs or otherwise proxying access to the Service or the Website nor is allowed to use the Service or the Website in an automated manner (that is by machine or computer program).</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">14. Copyright Policy</h2>
                <p>We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted with the use of the Service or on the Website infringes on the copyright or other intellectual property rights (“Infringement”) of any person or entity. If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright Infringement, please submit your claim via email to <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a>, with the subject line: “Copyright Infringement” and include in your claim a detailed description of the alleged Infringement as detailed below, under “DMCA Notice and Procedure for Copyright Infringement Claims”. You may be held accountable for damages (including costs and attorneys' fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through Service or Website on your copyright.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">15. DMCA Notice and Procedure for Copyright Infringement Claims</h2>
                <p>You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
                <ul className=" list-disc list-inside">
                    <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright's interest,</li>
                    <li>a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work,</li>
                    <li>identification of the URL or other specific location on Service where the material that you claim is infringing is located,</li>
                    <li>your address, telephone number, and email address,</li>
                    <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law,</li>
                    <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</li>
                </ul>
                <p>You can contact our Copyright Agent via email at <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a>.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">16. Error Reporting and Feedback</h2>
                <p>The Company tries – to the best of its ability – to support the Guests and Users in solving their problems related to functioning of the Service, as well as undertakes actions to improve the quality of the Service’s functioning and the provision of the Service based on the comments submitted by these entities.</p><p>You may provide us directly at <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a> with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service (“Feedback”). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialize) Feedback in any manner and for any purpose.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">17. Links to Other Websites</h2>
                <p>Our Service and/or Website may contain links to Other Websites that are not owned or controlled by the Company. The Company has no control over, and assumes no responsibility for the content, privacy policies, or practices of any Other Websites. We do not warrant the offerings of any of these entities/individuals or Other Websites. YOU ACKNOWLEDGE AND AGREE THAT THE COMPANY SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY OTHER WEBSITES. WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY OTHER WEBSITES THAT YOU VISIT.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">18. Disclaimer of Warranty</h2>
                <p>THE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE” BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK. NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">19. Limitation of Liability</h2>
                <p>The Company shall not be liable for the consequences of complying with the content of tips, articles or other publications on the Website or the Service, including the content provided by the AI computer. You acknowledge that the AI computer that provides the content in the Service and/or the Website is not the expert and may be mistaken and you cannot rely on its answers or advice. In particular it cannot replace any professional recommendation. The Company shall not be liable to the customers of the User for the use of the Service and the Content provided by the Service to the User’s customers.The Company shall not be liable for the consequences of installing or sending any malicious software, phishing or any other practises undertaken by other entities to the Service. The Company shall not be liable for any breaks in the operation of the Service. The Company shall not be liable for the consequences of phenomena known as force majeure, including in particular power outages, fires, atmospheric phenomena, wars, riots, strikes and other similar events that are not affected by the Company. EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS' FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THESE TERMS AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">20. The Guest’s/User’s Liability</h2><p>The Guest and/or User is fully liable for the consequences of authorised or unauthorised distribution of any content available on the Website or the Service. This applies in particular to the Intellectual Property. The liability includes, in particular, Company's release from any claims in this respect if such are against Company. The User is solely liable for any Content published, presented, sent or in any other way provided during the use of Service to the User’s customers.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">21. Service breaks</h2>
                <p>The Company does not guarantee the permanent accessibility of the Service or the Website. The Company reserves the right to introduce a break in the operation of the Website or the Service or their certain functionalities. If there is an intention to implement a break, the Company will notify about it by posting relevant information or a massage on the Website or via the email provided when setting-up the Account at least 3 days before the date of planned break. In the event of unintended breaks in the operation of the Website or the Service or their certain functionalities, the Company will immediately notify about it by posting a relevant information or message on the Website or via the email provided when setting-up the Account. Acceptance of the Regulations means also giving an approval for the Services being not 100% reliable.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">22. Personal Data Protection and Security</h2>
                <p>The Company processes personal data with due diligence and ensuring adequate technical and organizational security measures. Detailed information about the protection of personal data can be found in the Privacy Policy. The Company shall not be liable for the personal data protection of the User’s customers that use the Service. The Company shall not be liable for the contents and rules of personal data protection and privacy on the Other Websites, including those to which the Links refer. The Company shall not be liable for the damages caused by browsing the Other Websites or posting any personal data or other information on them. The Company recommends reading the rules of personal data protection and privacy on the Other Websites, including those to which the Links refer, before starting using them, in particular before publishing own personal data or other essential information on the Other Websites.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">23. Termination</h2>
                <p>We may terminate or suspend your Account and ban access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms. If you wish to terminate your Account, you may simply discontinue using Service. All provisions of Terms which, by their nature, should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">24. Governing Law</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of State of California without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">25. Changes To Service</h2>
                <p>We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">26. Amendments To Terms</h2>
                <p>We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically. Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently, so you are aware of any changes, as they are binding on you. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service. In case of any discrepancies between these Terms and the Agreement (if concluded), the provisions of the Agreement shall be applicable. The aforementioned sentence refers also to the amendments of these Terms introduced in the Agreement.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">27. Waiver And Severability</h2>
                <p>No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision. If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">28. Acknowledgement</h2>
                <p>BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.</p>
                <h2 className="w-full text-3xl text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 via-cyan-400 to-cyan-400 pb-3">29. Contact Us</h2>
                <p>Any time you wish to contact the Company, please send email at: <a href="mailto:support@cyanarrow.com">support@cyanarrow.com</a>.</p></div></div>
    </section>
  );
}
